name: runner-basics

on:
  workflow_dispatch:
    inputs: 
      target_runners:
        description: 'Self-hosted runner will run the job'
        required: true

jobs:
  test:
    runs-on:
    - ${{github.event.inputs.target_runners}}
    - ${{matrix.runner}}
    strategy:
      matrix:
        runner: [win-x64, linux-x64, osx-x64, linux-arm, linux-arm64]
    name: runner-basics (${{ matrix.runner }})
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Validate GitHub Context
      shell: bash
      run: |
        declare -a context_vars=("GITHUB_ACTION" "GITHUB_ACTIONS" "GITHUB_REPOSITORY" "GITHUB_WORKSPACE" "GITHUB_SHA" "GITHUB_RUN_ID" "GITHUB_RUN_NUMBER")
        for var in ${context_vars[@]};
        do [ -z "${!var}" ] && echo "##[error]$var not found" && exit 1 || echo "$var: ${!var}"; done
  
